### ISSUE TITLE
Contactready status is missing from the dashboard

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#126]
@magsout @laghee did you notice we never added the contactready graph. I'm not sure why? Maybe we just forgot.

**Comment by laghee** [comment]
@karlcow Huh. Maybe we did forget? 🤔 

I do have a vague memory about a discussion early on -- whether `needscontact` and `contactready` should be merged because how often did it happen that someone dug out a contact address but didn't actually go on to make the contact -- but I don't think it was ever answered decisively. Judging from a couple of the most recent bugs, `contactready` gets used often when it's an entity we've dealt with before or with whom we have an existing relationship. So certainly makes sense to keep it.

**Comment by karlcow** [comment]
ok. That makes sense. Let's add it, now we are tracking this a bit more closely. 
Thanks a lot @laghee for the context.

**Comment by karlcow** [comment]
We need to add the route.
https://webcompat-metrics.herokuapp.com/data/contactready-timeline?from=2019-09-14&to=2019-10-14

https://github.com/webcompat/webcompat-metrics-server/blob/d90b67ec726461e717c60690acb2a9305cc10efa/ochazuke/api/views.py#L54-L83

which probably means adding it to the list of valid categories.

https://github.com/webcompat/webcompat-metrics-server/blob/d90b67ec726461e717c60690acb2a9305cc10efa/ochazuke/helpers.py#L82-L88

should be an easy fix on the server side, we probably already collect the data?

**Comment by laghee** [comment]
@karlcow We actually were not already collecting the data 😊, but as of this evening (UTC) we are.  
![Screenshot 2019-10-28 20 03 03](https://user-images.githubusercontent.com/20972610/67709316-fbca8700-f9bd-11e9-91e0-f0116f66e1b5.png)

Won't be a pretty graph for a while, but at least this isn't a data point that probably changes all that dramatically.

**Comment by laghee** [comment]
Since the route is actually a template that works for all the hourly counted milestones, looks like we indeed only need to add `contactready` to the list of valid categories as mentioned above. Easy fix on this end!
