### ISSUE TITLE
params: from and to - end date should be inclusive.

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat-metrics-server#39]
@karlcow I'm looking for this issue https://github.com/webcompat/webcompat-metrics-client/issues/74

I noticed something. The API respond always one day less than the params sent.  

STR:
1) go to https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-20&to=2018-06-20
2) until 2018-06-19:
![image 2018-07-03 at 12 10 06 am](https://user-images.githubusercontent.com/1997108/42204153-b11e1da0-7e55-11e8-8891-4556b722efc6.png)

1) go to https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-20&to=2018-06-30
2) until 
![capture d ecran 2018-07-03 a 00 12 06](https://user-images.githubusercontent.com/1997108/42204166-bed62712-7e55-11e8-90a0-526edfc5eff8.png)

what do you think ?

In advance, I maybe missed something, I'm not good with dates/utc/tz

**Comment by laghee** [comment]
I think you're right, @magsout , because [the `datetime` objects](https://github.com/webcompat/webcompat-metrics-server/blob/21f568e615723abb868d426436d29eb1b235b3f1/ochazuke/helpers.py#L22) are set to midnight but naive (no TZ info), and the `timeline` json coming in from the github pipe is in UTC.

Since @karlcow is 9 hours ahead of UTC,  and github uses its utc timestamp to display events according to user location, issues that were filed at, say 17.00 GMT, show as the following day in Japan.

The easiest fix might be to add in an extra day in `get_days`, but it would be more accurate to incorporate TZ into the `datetime` objects. Or maybe there's a happy medium? Some way of doing a limited validation/normalization for only the first and last days in the list?

**Comment by karlcow** [comment]
Let's use the CLI

No parameters. Right now in JST. it is 15:50

```
→ http GET https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-timeline | tail -20
      "timestamp": "2018-08-22T01:59:59Z"
    },
    {
      "count": "250",
      "timestamp": "2018-08-22T02:59:59Z"
    },
    {
      "count": "250",
      "timestamp": "2018-08-22T04:00:00Z"
    },
    {
      "count": "245",
      "timestamp": "2018-08-22T04:59:59Z"
    },
    {
      "count": "241",
      "timestamp": "2018-08-22T05:59:59Z"
    }
  ]
}
```

so this is normal. Let's now query with a date range.
```
http GET 'https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-timeline?from=2018-08-20&to=2018-08-22'
```

```
    {
      "count": "251",
      "timestamp": "2018-08-21T18:59:59Z"
    },
    {
      "count": "251",
      "timestamp": "2018-08-21T19:59:59Z"
    },
    {
      "count": "251",
      "timestamp": "2018-08-21T20:59:59Z"
    },
    {
      "count": "251",
      "timestamp": "2018-08-21T21:59:59Z"
    },
    {
      "count": "251",
      "timestamp": "2018-08-21T22:59:59Z"
    }
  ]
}
```

ooops.

so what is happening is that I interpret 2018-08-22 as a until `2018-08-22T00:00:00` and not as a `2018-08-22T23:59:00`

This is not related to JST but to boundaries.

And it is exactly what my test was doing. 
https://github.com/webcompat/webcompat-metrics-server/blob/1b74f28e195df1c530799cf531a095c26e48fcbe/tests/unit/test_ochazuke.py#L107-L113

So I guess we need to change the logic for it.

**Comment by karlcow** [comment]
I will do that tomorrow.

**Comment by karlcow** [comment]
tests are broken because of #58, I will wait this is fixed before moving on.

**Comment by karlcow** [comment]
so this is finally fixed!
